### PR TITLE
add examples of prefixed/unprefixed job names

### PR DESCRIPTION
**Pull request by dwmarshall**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Review by minzcmu — APPROVED** [review]
👍

**Review by pranavrc — APPROVED** [review]
image

**Comment by dwmarshall** [comment]
I'll rebase and resubmit, hopefully that will fix the CLA check too.

**Pull request closed without merging**
