### PR TITLE
Fix alignments for `requires` and `annotations`

### PR DESCRIPTION
**Pull request by anilkumarmyla**
Fixes https://github.com/screwdriver-cd/screwdriver/issues/1112

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Review by minzcmu — APPROVED** [review]

**Review by tkyi — DISMISSED** [review]
Thank you!

**Review by jithine — CHANGES_REQUESTED** [review]
This yaml is not parsable in `/validator`

Use something like the following to use anchors properly
```
shared:
    template: nodejs/test@1.0.1
    annotations:
        foo: &bar
            requires: [~pr, ~commit]
            image: node:8

jobs:
    main:
        <<: *bar                 
        annotations:
            beta.screwdriver.cd/cpu: HIGH                      # Use HIGH for CPU
            screwdriver.cd/buildPeriodically: H H(4-7) * * *   # Run the job every day sometime between 4am and 7am UTC.
```

**Comment by tkyi** [comment]
Whoops! After rereviewing the PR with Jithin, I'm realizing that with anchors, your PR will not work
Please see @jithin1987 's comment ^

**Review by tkyi — APPROVED** [review]

**Comment by anilkumarmyla** [comment]
made changes per review comments

**Review by jithine — APPROVED** [review]

**Comment by jithine** [comment]
Thanks @anilkumarmyla for the fix.

**Pull request merged**
