### PR TITLE
docs(Japanese): translate commands.md

### PR DESCRIPTION
**Pull request by tk3fftk**
This PR translates `docs/user-guide/commands.md` into Japanese.

This is based on https://docs.screwdriver.cd/user-guide/commands .

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/160/ja/review/760)

### CODE REVIEW

**Review by s-yoshika — APPROVED** [review]

**Comment by yuichi10** [comment]
I think you need to add this page to [menu](https://github.com/screwdriver-cd/guide/blob/master/docs/_data/menu_ja.yml)

**Comment by tk3fftk** [comment]
@yuichi10 
thanks! I also added links which are not yet translated.

**Review by yuichi10 — APPROVED** [review]
LGTM

**Review by wdstar — APPROVED** [review]
:+1:

**Review by tkyi — APPROVED** [review]

**Pull request merged**
