### PR TITLE
fix: publish demo video

### PR DESCRIPTION
**Pull request by jithine**
Add to docs home page a video showcasing various Screwdriver features

screen shot 2018-07-13 at 3 33 37 pm

### CODE REVIEW

**Comment by tkyi** [comment]
Can you add a screenshot?
Also should this be added to the homepage (screwdriver.cd)?

**Comment by jithine** [comment]
@tkyi Added screenshot.

We can add it to the homepage later.

**Comment by tkyi** [comment]
Need to update Jekyll version since it's failing Snyk security checks.

**Review by Filbird — APPROVED** [review]

**Review by minzcmu — APPROVED** [review]

**Review by d2lam — APPROVED** [review]
👍

**Review by tkyi — APPROVED** [review]

**Pull request merged**
