### PR TITLE
fix: add docs for resource annotations

### PR DESCRIPTION
**Pull request by d2lam**
screen shot 2017-11-21 at 11 30 16 am

Related: 
https://github.com/screwdriver-cd/screwdriver/issues/758
https://github.com/screwdriver-cd/screwdriver/issues/759

### CODE REVIEW

**Review by petey — APPROVED** [review]
I thought we were going to have the CPU and Memory resource configurations separated. So you can upgrade CPU, or Memory, or both, as needed.

**Review by tkyi — APPROVED** [review]
LGTM 👍

**Comment by d2lam** [comment]
@petey We can also do that. Should be easy to fix. Maybe do it during HIP?

**Comment by tkyi** [comment]
I think we wanted to make sure users didn't go crazy and set something ridiculous

**Comment by petey** [comment]
We can still use HIGH/LOW. Just set them separately.

**Pull request merged**
