### PR TITLE
fix docker hub repository name

### PR DESCRIPTION
**Pull request by dchinmaya**
The images are available on [docker hub](https://hub.docker.com/r/screwdrivercd/screwdriver/) under the repository screwdrivercd. The doc looks for screwdriver-cd.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by dchinmaya** [comment]
Agreed to the CLA. Someone needs to rerun the check. 
Nevermind

**Review by FenrirUnbound — APPROVED** [review]
👍 

it s cold outside - imgur

**Review by tkyi — APPROVED** [review]

**Pull request merged**
