### PR TITLE
feat: create a Dockerfile that serves an instance of the guide

### PR DESCRIPTION
**Pull request by FenrirUnbound**
## Context

We want to host the Guide via Docker.

## Objective

* Create a Dockerfile for creating a Docker image.
* Publish Docker image to Docker Hub

### CODE REVIEW

**Review by tkyi — CHANGES_REQUESTED** [review]
Can you switch to using the scripts in the `toolbox` repo instead?
https://github.com/screwdriver-cd/toolbox

**Comment by tkyi** [comment]
Can switch it later if it's too much work

**Comment by FenrirUnbound** [comment]
> Can you switch to using the scripts in the toolbox repo instead?
https://github.com/screwdriver-cd/toolbox

I switched the `publish` job to using the toolbox. The `deploy` will change in the next couple of PRs so I'm not planning on change that if it's going to be overhauled soon.

**Comment by d2lam** [comment]
LGTM 👍

**Review by tkyi — APPROVED** [review]
LGTM

**Pull request merged**
