### PR TITLE
feat(371): Merging the bar into one row (fixing indentation)

### PR DESCRIPTION
**Pull request by stjohnjohnson**
Related to: https://github.com/screwdriver-cd/screwdriver/issues/371

before:
screen shot 2016-11-30 at 4 37 16 pm

after:
screen shot 2016-12-01 at 4 27 47 pm

### CODE REVIEW

**Review by tkyi — APPROVED** [review]

**Comment by d2lam** [comment]
Is it too cluttered? I feel like there should be at least some space between the logo & HOME. 
I sorta like the Before more, but I'm no UI designer...

**Comment by stjohnjohnson** [comment]
@d2lam I was trying to figure out how to add padding there, I'll play more with it.

**Comment by stjohnjohnson** [comment]
@d2lam fixed

**Review by minzcmu — APPROVED** [review]
Conflict! Otherwise LGTM 👍

**Comment by FenrirUnbound** [comment]
Looks a bit weird when the screen width shrinks between 768px-992px

screen shot 2016-12-02 at 4 16 31 pm

**Review by d2lam — APPROVED** [review]
LGTM 👍

**Review by FenrirUnbound — CHANGES_REQUESTED** [review]
Looks weird between `@screen-sm-min` and `@screen-md-min`. The double-row implementation didn't really experience this, but the single row has this weird inconsistency between the two screen sizes.

What about collapsing the navbar at a higher screen width than `@screen-sm-min`?

screen shot 2016-12-07 at 10 54 23 am

**Comment by stjohnjohnson** [comment]
Will look for an alternative in the future.

**Pull request closed without merging**
